---
- name: Securing the k3s cluster
  hosts: k3s_cluster
  tasks:
  - name: Switch to legacy iptables
    shell: |   
      iptables -F
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      exit 0
  
  - name: Enable Ip forwarding
    shell: |   
      sysctl -w net.ipv4.ip_forward=1
      wait 60
      exit 0

  - name: Install iptables-persistent
    apt:
      name:
        - iptables-persistent
      update_cache: yes
      state: present

  - name: Create iptables directory if it does not exist
    file:
      path: /etc/iptables/
      state: directory
      mode: '0755'

  - name: Copy iptables rules v4
    copy:
      src: ./iptables-rules/rules.v4
      dest: /etc/iptables/rules.v4

  - name: Reboot the machine (Wait for 5 min)
    reboot:
      msg: "the server will reboot"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami