authors:
- Matthew Kalnins <github@mattykay.com>
- k3s-io community
build_ignore: []
dependencies:
  ansible.posix: '>=1.5.0'
  community.general: '>=7.0.0'
description: Build a Kubernetes cluster using K3s via Ansible
documentation: https://github.com/k3s-io/k3s-ansible/blob/main/README.md
homepage: https://github.com/k3s-io/k3s-ansible
issues: https://github.com/k3s-io/k3s-ansible/issues
license:
- Apache-2.0
name: k3s_ansible
namespace: mattykay
readme: README.md
repository: https://github.com/k3s-io/k3s-ansible
tags:
- infrastructure
- linux
- tools
version: 1.1.1
