---

- hosts: load_balancer
  gather_facts: yes
  become: no
  roles:
    - role: apt_dependencies
    - role: ntp
    - role: consul/node
      vars:
        consul_master: yes
        master_list:
          - "lb1.local"
    - role: haproxy
      vars:
        priority: lb_priority
        # Not really necessary to specify everything, but it's better to be explicit
        internal_interface: internal_interface
        internal_floating_ip: external_floating_ip
        external_interface: external_interface
        external_floating_ip: external_floating_ip
