---

- name: "Setup K3s Cluster"
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- name: "Server Setup"
  hosts: master
  become: yes
  roles:
    - role: k3s/master  # noqa: role-name[path]

- name: "Agent Setup"
  hosts: node
  become: yes
  roles:
    - role: k3s/node  # noqa: role-name[path]
