---

- hosts: 127.0.0.1
  connection: local
  roles:
    - role: config-check

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: server
  become: yes
  roles:
    - role: k3s/server

- hosts: server
  tasks:
    - name: Copy .kube/config for new cluster
      fetch:
        src: "~{{ ansible_user }}/.kube/config"
        dest: ./cluster.config
        flat: yes
      run_once: true

- hosts: agent
  become: yes
  roles:
    - role: k3s/agent

