provider:
  name: google

domainFilters: [robertbatson.com]

txtOwnerId: homelab-k3s

extraArgs:
- --google-project=robertb724-personal

env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/secrets/service-account/credentials.json

extraVolumeMounts:
  - name: google-service-account
    mountPath: /etc/secrets/service-account/

extraVolumes:
  - name: google-service-account
    secret:
      secretName: gcp-sa-key
