---

- name: Include vars
  include_vars: "../roles/ha/keepalived/defaults/main.yml"

###################
# Stop the service

- name: Stop keepalived service
  service:
    name: keepalived
    enabled: no
    state: stopped

##################################
# Delete the configuration

- name: Delete the keepalived configuration
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ keepalived_etc_dir }}"
    - "{{ keepalived_lib_dir }}"
    - "{{ keepalived_run_dir }}/{{ keepalived_script_output }}"
#   - "{{ keepalived_etc_dir }}/{{ keepalived_config_file }}"
#   - "{{ keepalived_lib_dir }}/{{ keepalived_script_name }}"
#   - "{{ keepalived_lib_dir }}/{{ keepalived_script_kubeconfig }}"

- name: Remove keepalived script user, {{ keepalived_script_user }}
  user:
    name: "{{ keepalived_script_user }}"
    state: absent
    remove: yes
    force: yes

##################################
# Uninstall the keepalived package

- name: Uninstall package keepalived
  package:
    name: keepalived
    state: absent
  when: keepalived_package_remove | bool

