---
- name: Add cgroup mount point
  lineinfile:
    path: /etc/fstab
    line: cgroup /sys/fs/cgroup cgroup defaults 0 0

- name: Define cgroup mount points
  copy:
    content: |
      mount {
        cpuacct = /cgroup/cpuacct;
        memory = /cgroup/memory;
        devices = /cgroup/devices;
        freezer = /cgroup/freezer;
        net_cls = /cgroup/net_cls;
        blkio = /cgroup/blkio;
        cpuset = /cgroup/cpuset;
        cpu = /cgroup/cpu;
      }
    dest: /etc/cgconfig.conf
    mode: 0644

- name: Enable cgroup via boot commandline if not already enabled
  lineinfile:
    path: /media/mmcblk0p1/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify: lbu
