---
- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot
