---
- name: Check for correct server configuration (1 = non-HA; 3+ = HA)
  fail:
    msg: "HA configuration requires a minimum of three (3) servers."
  when: groups['k3s_server'] | length == 2

- name: Determine version to download
  block:
    - name: Determine version from channel
      vars:
          version_url: "{{ k3s_channel_url }}/{{ k3s_channel }}"
      block:
        - name: Output channel information
          debug:
            var: version_url
          when: report_version_info

        - name: Get version from channel
          uri:
            url: "{{ version_url }}"
            follow_redirects: safe
            force: yes
            return_content: no
          register: channel_version_info

        - name: Set version from channel
          set_fact:
            k3s_version: "{{ channel_version_info.url.split('/')[-1] }}"

      when: k3s_version == 'undefined'

    - name: Output version
      debug:
        var: k3s_version
      when: report_version_info

  when: k3s_commit == 'undefined'
  check_mode: no

- name: Check for minimum k3s version for HA configuration
  fail:
    msg: "HA configurations require k3s v1.19.5+k3s1 or greater.  {{ k3s_version }} was specified."
  vars:
    short_version: "{{ k3s_version | regex_search('v([^+]+)+', '\\1') | first }}"
  when:
    - k3s_commit == 'undefined'
    - groups['k3s_server'] | length >= 3
    - short_version is version('1.19.5', 'lt', True)

- name: No check when k3s_commit is specified
  debug:
    msg: "There is no version check for HA support when a k3s_commit is specified.  We assume you know what you are doing."
  when:
    - k3s_commit != 'undefined'
    - groups['k3s_server'] | length >= 3
    - report_version_info

