---
- name: Check for correct single server configuration
  fail:
    msg: "Single server configuration requires exactly one (1) server."
  when:
    - not ha_enabled
    - groups['k3s_server'] | length != 1

# Purposefully do the HA check in two steps
- name: Check for correct HA configuration (minimum)
  fail:
    msg: "HA configuration requires an odd number of servers > 1 (i.e., minimum is three)."
  when:
    - ha_enabled
    - groups['k3s_server'] | length < 3

- name: Check for correct HA configuration (odd number)
  fail:
    msg: "HA configuration requires an ODD number of servers."
  when:
    - ha_enabled
    - groups['k3s_server'] | length is divisibleby 2

- name: Check for a proper HA cluster virtual IP
  fail:
    msg: "When HA is enabled, 'ha_cluster_vip' must have a valid IP address."
  when:
    - ha_enabled
    - (ha_cluster_vip is not defined) or not (ha_cluster_vip | ansible.netcommon.ipaddr)

- name: Check for a proper HA cluster method
  fail:
    msg: "'{{ k3s_cluster_method }}' is not a supported HA cluster method."
  when:
    - ha_enabled
    - k3s_cluster_method not in k3s_cluster_methods

- name: Determine version to download
  block:
    - name: Determine version from channel
      vars:
          version_url: "{{ k3s_channel_url }}/{{ k3s_channel }}"
      block:
        - name: Output channel information
          debug:
            var: version_url
          when: report_version_info

        - name: Get version from channel
          uri:
            url: "{{ version_url }}"
            follow_redirects: safe
            force: yes
            return_content: no
          register: channel_version_info

        - name: Set version from channel
          set_fact:
            k3s_version: "{{ channel_version_info.url.split('/')[-1] }}"

      when: k3s_version == 'undefined'

    - name: Output version
      debug:
        var: k3s_version
      when: report_version_info

  when: k3s_commit == 'undefined'
  check_mode: no

- name: Check for minimum k3s version for HA configuration
  fail:
    msg: "HA configurations require k3s v1.19.5+k3s1 or greater.  {{ k3s_version }} was specified."
  vars:
    short_version: "{{ k3s_version | regex_search('v([^+]+)+', '\\1') | first }}"
  when:
    - k3s_commit == 'undefined'
    - ha_enabled
    - short_version is version('1.19.5', 'lt', True)

- name: No check when k3s_commit is specified
  debug:
    msg: "There is no version check for HA support when a k3s_commit is specified.  We assume you know what you are doing."
  when:
    - k3s_commit != 'undefined'
    - ha_enabled
    - report_version_info

