---
k3s_version: v1.17.5+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""


consul_domain_suffix: "cluster"
internal_floating_ip: "10.0.0.1"
internal_interface: "eth0"
external_floating_ip: "192.168.50.150"
external_interface: "eth0"