---
- name: Enable net.ipv4.ip_nonlocal_bind
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
  become: yes

- name: Install keepalived
  apt:
    name: keepalived
    state: latest
  become: yes

- name: Add keepalived configuration
  ansible.builtin.template:
    src: "{{ role_path }}/templates/keepalived.conf.j2"
    dest: /etc/keepalived/keepalived.conf
  become: yes

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: yes
  become: yes
...
