---
- name: Run apt dist-upgrade
  apt:
    upgrade: dist
    update_cache: yes
  become: yes

- name: Install apt dependencies
  apt:
    pkg:
    - curl
    - dnsutils
    - git
    - gnupg
    - jq
    - software-properties-common
    - unzip
    state: latest
  become: yes

- name: Disable ipv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present
  become: yes

- name: Disable ipv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    state: present
  become: yes
...