---

- name: Copy K3S environment file
  ansible.legacy.template:
    src: "k3s.service.env.j2"
    dest: "{{ k3s_systemd_dir }}/k3s.service.env"
    owner: root
    group: root
    mode: 0644
  notify: Restart K3S service

- name: Copy K3S service file
  ansible.legacy.template:
    src: "k3s.service.j2"
    dest: "{{ k3s_systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644
  notify: Restart K3S service
