---
all:
  vars:
    ansible_user: pi
  children:
    k3s_cluster:
    load_balancer:

k3s_cluster:
  vars:
    ansible_ssh_common_args: '-o ForwardAgent=yes -o ProxyCommand="ssh -W %h:%p -q pi@lb1.local"'
  children:
    master:
    node:

master:
  hosts:
    master1:
      ansible_host: master1.local
    master2:
      ansible_host: master2.local

node:
  hosts:
    node1:
      ansible_host: node1.local
    node2:
      ansible_host: node2.local

load_balancer:
  hosts:
    lb1:
      ansible_host: lb1.local
      lb_priority: 100
      internal_cidr: 10.0.0.2/16
    lb2:
      ansible_host: lb2.local
      lb_priority: 99
      internal_cidr: 10.0.0.3/16
...
