---
name: Build
on:
  push:
    branches:
      - main

jobs:

  test:
    name: Build Ansible Galaxy collection artifact.
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python 3.13.
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13.x'

      - name: Install test dependencies.
        run: pip3 install ansible

      - name: Build artifact.
        run: ansible-galaxy collection build

      - name: Upload artifact.
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: galaxy-collection
          path: k3s-orchestration-*.tar.gz
