---
name: Lint
'on':
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.10.
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install test dependencies.
        run: pip install yamllint ansible-lint ansible

      - name: Run yamllint.
        run: yamllint .

      - name: Run ansible-lint.
        run: ansible-lint
